version: '3'

services:
  mongodb:
    image: mongo
    command: --auth
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
    env_file:
      - ./backend/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  backend:
    build: ./backend
    ports:
      - "3000:8000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
